# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.6
  # - nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
notifications:
  email: false
addons:
  apt:
    packages:
    - libzmq3
# script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.checkout("RigidBodyDynamics"); Pkg.checkout("RigidBodyTreeInspector"); Pkg.checkout("RigidBodySim"); Pkg.build("MomentumBasedControl"); Pkg.test("MomentumBasedControl"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("MomentumBasedControl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
